apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubesftp.fullname" . }}-users
  labels:
    {{- include "kubesftp.labels" . | nindent 4 }}
data:
  users.conf: |
{{- range .Values.sftpUsers }}
    {{ . }}
{{- end }}
