apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubesftp.fullname" . }}
  labels:
    {{- include "kubesftp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "kubesftp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubesftp.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubesftp.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
      - name: generator
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
          - /usr/local/bin/generator
        env:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: HOST_KEYS_SECRET
          value: {{ .Values.hostKeysSecret | default (printf "%s-host-keys" (include "kubesftp.fullname" .)) }}
        - name: CONFIG_FILE_PATH
          value: /config/config.yaml
        restartPolicy: Never
        volumeMounts:
        - name: etc
          mountPath: /mnt/etc
        - name: config
          mountPath: /config
          readOnly: true
        - name: chroots
          mountPath: /chroots
      - name: monitor
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        command:
          - /usr/local/bin/monitor
        env:
        - name: CONFIG_FILE_PATH
          value: /config/config.yaml
        restartPolicy: Always
        volumeMounts:
        - name: chroots
          mountPath: /chroots
        - name: config
          mountPath: /config
          readOnly: true
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        volumeMounts:
        - name: etc
          mountPath: /etc/ssh
          subPath: ssh
        - name: etc
          mountPath: /etc/passwd
          subPath: passwd
        - name: etc
          mountPath: /etc/shadow
          subPath: shadow
        - name: etc
          mountPath: /etc/group
          subPath: group
        - name: chroots
          mountPath: /chroots
      volumes:
      - name: config
        configMap:
          name: {{ include "kubesftp.fullname" . }}
      - name: etc
        emptyDir: {}
      - name: chroots
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
