{{- if or .Values.sshHostKeys.rsa .Values.sshHostKeys.dsa .Values.sshHostKeys.ecdsa .Values.sshHostKeys.ed25519 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubesftp.fullname" . }}-host-keys
  labels:
    {{- include "kubesftp.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.sshHostKeys.rsa }}
  ssh_host_rsa_key: {{ .Values.sshHostKeys.rsa | b64enc }}
  {{- end }}
  {{- if .Values.sshHostKeys.dsa }}
  ssh_host_dsa_key: {{ .Values.sshHostKeys.dsa | b64enc }}
  {{- end }}
  {{- if .Values.sshHostKeys.ecdsa }}
  ssh_host_ecdsa_key: {{ .Values.sshHostKeys.ecdsa | b64enc }}
  {{- end }}
  {{- if .Values.sshHostKeys.ed25519 }}
  ssh_host_ed25519_key: {{ .Values.sshHostKeys.ed25519 | b64enc }}
  {{- end }}
{{- end }}
