apiVersion: v2
name: kubesftp
description: A Helm chart for deploying a stateless SFTP/SSH server using OpenSSH on Kubernetes
type: application
version: 0.1.0
appVersion: "1.0.0"
keywords:
  - sftp
  - ssh
  - openssh
  - file-transfer
home: https://github.com/leg100/kubesftp
sources:
  - https://github.com/leg100/kubesftp
maintainers:
  - name: kubesftp
    url: https://github.com/leg100/kubesftp
